development:
  cloud_name: hbomkkuxz
  api_key: '774115666331229'
  api_secret: YZaiBGREwOrPYV5gmYd8tYu-X_I
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hbomkkuxz
  api_key: '774115666331229'
  api_secret: YZaiBGREwOrPYV5gmYd8tYu-X_I
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hbomkkuxz
  api_key: '774115666331229'
  api_secret: YZaiBGREwOrPYV5gmYd8tYu-X_I
  enhance_image_tag: true
  static_image_support: false